services:
  - type: web
    name: venda-definitiva
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SETTINGS_MODULE
        value: delivery_system.settings
      - key: DEBUG
        value: false
