# Generated by Django 5.2.5 on 2025-08-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Total de pedidos')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='Pedidos completados')),
                ('cancelled_orders', models.PositiveIntegerField(default=0, verbose_name='Pedidos cancelados')),
                ('failed_orders', models.PositiveIntegerField(default=0, verbose_name='Pedidos que falharam')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Receita total')),
                ('average_delivery_time', models.PositiveIntegerField(default=0, verbose_name='Tempo médio de entrega (minutos)')),
                ('active_motoboys', models.PositiveIntegerField(default=0, verbose_name='Motoboys ativos')),
                ('total_motoboys', models.PositiveIntegerField(default=0, verbose_name='Total de motoboys')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Avaliação média')),
                ('customer_satisfaction', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Satisfação do cliente (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Estatística de Entrega',
                'verbose_name_plural': 'Estatísticas de Entregas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MotoboyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total de entregas')),
                ('successful_deliveries', models.PositiveIntegerField(default=0, verbose_name='Entregas com sucesso')),
                ('failed_deliveries', models.PositiveIntegerField(default=0, verbose_name='Entregas que falharam')),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Distância total (km)')),
                ('average_delivery_time', models.PositiveIntegerField(default=0, verbose_name='Tempo médio de entrega (minutos)')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Avaliação média')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ganhos totais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Performance do Motoboy',
                'verbose_name_plural': 'Performance dos Motoboys',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
