# Generated by Django 5.2.5 on 2025-08-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('motoboys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboyperformance',
            name='motoboy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motoboys.motoboy', verbose_name='Motoboy'),
        ),
        migrations.AlterUniqueTogether(
            name='motoboyperformance',
            unique_together={('motoboy', 'month', 'year')},
        ),
    ]
