# Generated by Django 5.2.5 on 2025-08-27 22:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('document_type', models.CharField(choices=[('cpf', 'CPF'), ('cnh', 'CNH'), ('rg', 'RG')], max_length=3, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Número do documento')),
                ('vehicle_model', models.CharField(max_length=100, verbose_name='Modelo da moto')),
                ('vehicle_plate', models.CharField(max_length=10, verbose_name='Placa da moto')),
                ('vehicle_year', models.PositiveIntegerField(verbose_name='Ano da moto')),
                ('vehicle_color', models.CharField(max_length=50, verbose_name='Cor da moto')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude atual')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude atual')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='Última atualização de localização')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('busy', 'Ocupado'), ('offline', 'Offline'), ('suspended', 'Suspenso')], default='offline', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Avaliação')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='Total de entregas')),
                ('successful_deliveries', models.PositiveIntegerField(default=0, verbose_name='Entregas com sucesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Motoboy',
                'verbose_name_plural': 'Motoboys',
                'ordering': ['-created_at'],
            },
        ),
    ]
