# Generated by Django 5.1.5 on 2025-08-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoboys', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoboy',
            name='device_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='IDs dos dispositivos'),
        ),
    ]
