# Generated by Django 5.2.5 on 2025-08-27 22:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número do pedido')),
                ('pickup_address', models.TextField(verbose_name='Endereço de retirada')),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de retirada')),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de retirada')),
                ('delivery_address', models.TextField(verbose_name='Endereço de entrega')),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude de entrega')),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude de entrega')),
                ('description', models.TextField(verbose_name='Descrição do pedido')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Dimensões')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Frágil')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('picked_up', 'Retirado'), ('in_transit', 'Em trânsito'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço base')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distância (km)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço final')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação (1-5)')),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback do cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de aceitação')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de retirada')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de entrega')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('estimated_delivery_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo estimado de entrega (minutos)')),
                ('actual_delivery_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo real de entrega (minutos)')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
