# Generated by Django 5.1.5 on 2025-08-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuitem_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dimensions',
            field=models.CharField(blank=True, default='Padrão', max_length=100, verbose_name='Dimensões'),
        ),
    ]
